-- Add user table
CREATE TABLE user (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT COLLATE NOCASE NOT NULL UNIQUE,
	email TEXT COLLATE NOCASE NOT NULL UNIQUE,
	bio TEXT NOT NULL DEFAULT '',
	password TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP
);
